# Generated by Django 4.0 on 2022-06-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('A', 'Active'), ('P', 'Processing'), ('F', 'Finished')], default='W', max_length=1)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_player', models.BooleanField(default=True)),
                ('is_creator', models.BooleanField(default=False)),
                ('is_validator', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=-1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.profile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.category')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=120)),
                ('letter', models.CharField(max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.category')),
            ],
        ),
        migrations.CreateModel(
            name='GameWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.profile')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.word')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='chat.profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='chat.profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.task'),
        ),
        migrations.AddField(
            model_name='game',
            name='words',
            field=models.ManyToManyField(through='chat.GameWord', to='chat.Word'),
        ),
        migrations.AddField(
            model_name='category',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.profile'),
        ),
    ]
